# Generated by Django 4.2.7 on 2023-12-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('is_meat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.BooleanField(blank=True, null=True)),
                ('vegetarian', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='IngredientsPairs',
            fields=[
                ('ingredient_name', models.OneToOneField(blank=True, db_column='ingredient_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='food.ingredients')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('recipe_name', models.ForeignKey(blank=True, db_column='recipe_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='food.recipes')),
            ],
            options={
                'db_table': 'ingredients_pairs',
            },
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('username', models.OneToOneField(blank=True, db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='food.profiles')),
                ('ingredient_name', models.ForeignKey(blank=True, db_column='ingredient_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='food.ingredients')),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
    ]
